### ISSUE TITLE
Ver 2.0 Color 입히기

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#217]
## 🛠 Issue
- 모든 뷰 컬러 적용

## 📝 To-do
- [x] 런치스크린
- [x] 온보딩뷰
- [ ] 메인뷰
- [x] 보관함
- [x] 검색
- [x] 아티스트뷰
- [x] 세트리스트뷰
- [x] 설정

**Comment by Yeeunlee34** [comment]
아주 훌륭합니다
