### ISSUE TITLE
세트리스트 뷰 수정

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#221]
## 🛠 Issue
- 세트리스트 뷰 수정

## 📝 To-do
- [ ] 플레이리스트 내보내기 모달
- [ ] 토스트 메시지
- [ ] 플레이리스트 제목 설정
- [ ] 공유하기뷰 연결

**Comment by Yeeunlee34** [comment]
화이팅하세요~~
