### ISSUE TITLE
Tuist와 SwiftLint의 충돌로 인해 컴파일 안되는 문제

### ISSUE THREAD

**Issue by Oreo-Mcflurry** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#25]
## 🐛 Description
[현재 디벨롭 브랜치에서 빌드]시, [command phasescriptexecution failed with a nonzero exit code]가 발생합니다.

## 📝 TODO
- [x] SwiftLint 충돌문제 해결하기

**Comment by sumintnals** [comment]
awesome!
