### ISSUE TITLE
MainView 스타일 바꾸기

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#41]
## 🛠 Issue
- 메인 뷰의 다크모드 버튼 스타일과, 아티스트 이름을 두줄로 바꾸는 것 구현하기

## 📝 To-do
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/f80f7a12-e96d-42d4-a6cc-b602dded534b)
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/f1f20da9-f2ca-499a-9487-b27a411c0250)

- [ ] 다크모드 버튼 수정
- [ ] 아티스트 이름 길 때 두줄로 바꾸기(첫 번째 공백에서 줄바꿈)

**Comment by Ko-HyeJi** [comment]
스타일 좋으시네요~ Dm 보냅니다.
