### ISSUE TITLE
검색 버그 수정 + Combine 적용

### ISSUE THREAD

**Issue by Oreo-Mcflurry** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#52]
## 🐛 Description
1. [영어로 Exo를 검색했을때] 아무것도 안나오는 버그 발생
+) 다른 나라 exo를 선택했을 때 한국 exo 사진이 들어가는 문제..!

2. Sam Smith 세트리스트를 받아오지 못하는 문제

3. 검색 결과 사이에 공백 들어감

4. br 쳤을 때 이상한 결과 나옴

5. 검색어 자동 수정 막기

6. 검정치마 Genius에서 못찾음

## 📝 TODO
- [ ] Exo 구출작전
- [ ] 검정치마 구출작전

**Comment by Ko-HyeJi** [comment]
가수 이름을 비교할 때 대소문자를 구분하지 않아서 정확도가 떨어짐... 근데 대소문자 구분을 하면 못찾을 가능성이 높아짐... 어쩌지..?
